version: '3.7'

services:
  web:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 Notatki.wsgi
    volumes:
      - static_data:/vol/web
    expose:
      - 8000



  proxy:
    build: ./proxy
    ports:
      - 443:443
    depends_on:
      - web


volumes:
  static_data: