# Generated by Django 4.0 on 2021-12-20 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='users_with_permission_to_view',
            field=models.ManyToManyField(related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='auth.user'),
        ),
        migrations.DeleteModel(
            name='SharedNote',
        ),
    ]
