# Generated by Django 4.0 on 2021-12-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_note_users_with_permission_to_view_alter_note_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptednote',
            name='aes_key',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
    ]
