# Generated by Django 4.0 on 2021-12-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_encryptednote_aes_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptednote',
            name='aes_key',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='encryptednote',
            name='password',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='encryptednote',
            name='salt',
            field=models.BinaryField(),
        ),
    ]
